# Generated by Django 5.2.14 on 2026-05-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('meat', "Go'sht"), ('rice', 'Guruch'), ('milk', 'Sut mahsulotlari')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.product')),
            ],
            options={
                'verbose_name': 'Oylik narx',
                'verbose_name_plural': 'Oylik narxlar',
                'ordering': ['year', 'month'],
                'unique_together': {('product', 'year', 'month')},
            },
        ),
    ]
